apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: flux
  generation: 1
  labels:
    name: flux
  name: flux
  selfLink: /apis/extensions/v1beta1/namespaces/flux/deployments/flux
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "3031"
      creationTimestamp: null
      labels:
        name: flux
    spec:
      containers:
      - args:
        - --memcached-service=
#        - --git-url=https://dmitri-at-next:$(GITHUBTOKEN)@github.com/dmitri-at-next/friendly-apps.git
        - --git-poll-interval=1m
        - --git-timeout=60s
        - --git-branch=master
        - --git-secret=false
        image: docker.io/fluxcd/flux:1.15.0
        env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: githubtoken
              key: githubtoken
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/flux/v6/identity.pub
            port: 3030
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: flux
        ports:
        - containerPort: 3030
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/flux/v6/identity.pub
            port: 3030
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/fluxd/ssh
          name: git-key
          readOnly: true
        - mountPath: /var/fluxd/keygen
          name: git-keygen
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: flux
      serviceAccountName: flux
      terminationGracePeriodSeconds: 30
      volumes:
      - name: git-key
        secret:
          defaultMode: 256
          secretName: flux-git-deploy
      - emptyDir:
          medium: Memory
        name: git-keygen
status: {}
